sudo: false

language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

script:
    - git clone --depth=1 https://github.com/jedisct1/libsodium.git --branch=stable
    - make CFLAGS=-std=c99 CPPFLAGS="-D_GNU_SOURCE -I./libsodium/src/libsodium/include" mud.o
